### ISSUE TITLE
[BACKEND-FEATURE] Upload and remove completed downloads

### ISSUE THREAD

**Issue by mjrode** [mjrode/audible#20]
## Description 
Upload audiobook after the download is complete
## Items
- [x] Check on status of transmission downloads
- [x] If a file is in `/books/incomplete` and finished downloading upload the file to google drive
- [x] Delete the torrent after successfully uploaded
